# fly.toml app configuration file generated for joex-db-engine-wandering-grass-7853 on 2026-07-24T15:36:15+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'joex-db-engine-wandering-grass-7853'
primary_region = 'cdg'

[build]
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
