<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests\**" />
    <Compile Remove="JOEX_DB_Engine.Tests\**" />
    <Content Remove="Tests\**" />
    <Content Remove="JOEX_DB_Engine.Tests\**" />
    <EmbeddedResource Remove="Tests\**" />
    <EmbeddedResource Remove="JOEX_DB_Engine.Tests\**" />
    <None Remove="Tests\**" />
    <None Remove="JOEX_DB_Engine.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1" />
  </ItemGroup>

</Project>
